Resources:
  SitesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.table}
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "version"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
        - AttributeName: "path"
          AttributeType: "S"
        - AttributeName: "updatedAt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "version"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      GlobalSecondaryIndexes:
        - IndexName: "type-path-index"
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
            - AttributeName: "path"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - IndexName: "path-updatedAt-index"
          KeySchema:
            - AttributeName: "path"
              KeyType: "HASH"
            - AttributeName: "updatedAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - IndexName: "path-version-index"
          KeySchema:
            - AttributeName: "path"
              KeyType: "HASH"
            - AttributeName: "version"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      LocalSecondaryIndexes:
        - IndexName: "id-updatedAt-index"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
            - AttributeName: "updatedAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
