# For full config options, check the docs: docs.serverless.com
service: go-lambda-dynamo # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  table: ${opt:table, 'go-lambda-dynamo'}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    TABLE_NAME: ${self:provider.table}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: sites
          method: post
          cors: true
  delete:
    handler: bin/delete
    events:
      - http:
          path: sites/{id}
          method: delete
          cors: true
  get:
    handler: bin/get
    events:
      - http:
          path: sites/{id}
          method: get
          cors: true
  list:
    handler: bin/list
    events:
      - http:
          path: sites
          method: get
          cors: true

resources:
  - ${file(dynamodb.yml)}
