# For full config options, check the docs: docs.serverless.com
service: go-lambda-dynamo # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  table: ${opt:table, 'go-lambda-dynamo'}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    TABLE_NAME: ${self:provider.table}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  CreateSite:
    handler: bin/sites/create
    events:
      - http:
          path: sites
          method: post
          cors: true
  DeleteSite:
    handler: bin/sites/delete
    events:
      - http:
          path: sites/{siteid}
          method: delete
          cors: true
  GetSite:
    handler: bin/sites/get
    events:
      - http:
          path: sites/{siteid}
          method: get
          cors: true
  ListSites:
    handler: bin/sites/list
    events:
      - http:
          path: sites
          method: get
          cors: true
  UpdateSite:
    handler: bin/sites/update
    events:
      - http:
          path: sites/{siteid}
          method: patch
          cors: true
  CreatePage:
    handler: bin/pages/create
    events:
      - http:
          path: sites/{siteid}/pages
          method: post
          cors: true
  DeletePage:
    handler: bin/pages/delete
    events:
      - http:
          path: sites/{siteid}/pages/{pageid}
          method: delete
          cors: true
  GetPage:
    handler: bin/pages/get
    events:
      - http:
          path: sites/{siteid}/pages/{pageid}
          method: get
          cors: true
  ListPages:
    handler: bin/pages/list
    events:
      - http:
          path: sites/{siteid}/pages
          method: get
          cors: true
  UpdatePage:
    handler: bin/pages/update
    events:
      - http:
          path: sites/{siteid}/pages/{pageid}
          method: patch
          cors: true

resources:
  - ${file(dynamodb.yml)}
